version: '3.4'

services:
  notebook:
    image: sensorium
    build:
      context: .
    volumes:
      - .:/project
      - ./notebooks:/notebooks
    env_file:
      - .env

  jupyterlab:
    image: sensorium
    build:
      context: .
    volumes:
      - .:/project
      - ./notebooks:/notebooks
    environment:
      - JUPYTER_PASSWORD=
